import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/administration/logger">
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Logger &rarr;</h2>
              <p>application to search and list applications Logger!</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
